SELECT REVIEWS.LISTING_ID, REVIEWS.REVIEW_DATE, DIM.CREATED_AT FROM 
{{ ref('fct_reviews') }} AS REVIEWS 
INNER JOIN 
{{ ref('dim_listings_cleansed') }} AS DIM
ON REVIEWS.LISTING_ID = DIM.LISTING_ID
WHERE REVIEWS.REVIEW_DATE < DIM.CREATED_AT