services:
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:  
    volumes:
      - "./mongo:/data/db"
